version: '3.8'

services:
  # PHP Application Service
  app:
    image: projectdocflix/mediflix:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes: 
      - ./.env:/var/www/html/.env
      - upload_data:/var/www/html/uploads
      - public_data:/var/www/html/public
      - resources_data:/var/www/html/resources
      - storage_data:/var/www/html/storage
    networks:
      - laravelnet
    depends_on:
      - db

  # Nginx Web Server Service
  webserver:
    image: projectdocflix/mediflix-serv:latest
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - upload_data:/var/www/html/uploads
      - public_data:/var/www/html/public
      - resources_data:/var/www/html/resources
      - storage_data:/var/www/html/storage
    networks:
      - laravelnet
    depends_on:
      - app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravelnet

# Docker Networks
networks:
  laravelnet:
    driver: bridge

# Named Volume for Persistent Data
volumes:
  dbdata:
    driver: local
  public_data:
    driver: local
  resources_data:
    driver: local
  storage_data:
    driver: local
  upload_data:
    driver: local
